### ISSUE TITLE
pomišljaj vs. dolgi pomišljaj

### ISSUE THREAD

**Issue by jvadn-gh** [mikanovic-svg/kapital_02#2]
Je kakšen poseben razlog, da se pomišljaje piše kot dolgi pomišljaj? V Latexu torej '---' namesto '--'. Če bo v originalnem besedilu kje uporabljen dolgi pomišljaj (npr. pri razbijanju dolgih povedi), bomo v frki glede izbire ustreznega znaka.

**Comment by mikanovic-svg** [comment]
Katere točno misliš? Na katerem mestu si opazil? Če prav razumem je besedilo polno teh, in kjer je besedilo že obdelano sem to upošteval (vsaj mislim)

Uporabo različnih pomišljajev sebi najlažje razložim takole:
-: ko nadomešča "in" (politično-ekonomski), ko gre za "dvojno" ime (C-vitamin, 3-kotnik);
--: ko gre za razpone (1919--1934, strani 187--192)
---: razbijanje povedi, vrinjeni stavki (če prav razumem je besedilo polno teh in kjer je besedilo že obdelano sem to upošteval)

Ustreznega znaka med raznimi Bji, Dji in Pji še nisem našel. Zaenkrat je tekst stavljen tako da semantično razlikuje med besedilom in marxovimi formulami (z math modeom), ampak tam ni vezajev, samo minus (-), ki je imo prekratek in latex mu da preveč presledkov okoli. Za ta znak sem rezerviral lasten command (\KPEcrta) tako da se lahko centralno ureja, ko najdemo ustrezno rešitev.

**Comment by jvadn-gh** [comment]
Npr. na str. 57 lahko vidiš uporabo vseh možnosti: kar jaz pravim je, da je tudi v primeru "... nenavadna oblika - se pravi ..." (iz vrhnjega odstavka na str. 57) v originalnem tekstu uporabljen pomišljaj dolžine '--', t.j. enako kot v spodnjem odstavku, ko navaja strani iz 1. knjige (namesto "od ... do"). Sem šel tudi pomerit in je približno ista dolžina črte v obeh primerih.
Tudi kar sva se prejšnjo nedeljo pogovarjala o pomišljajih v opombah - tudi to sem preveril in črte so krajše, ker je font opomb pomanjšan (primer: Engelsova opomba o latentnosti). Ampak če primerjaš npr. višino malega L in dolžino pomišljaja, se razmerje ohranja med opombami in glavnim besedilom.
Rešitve za črto v izrazih žal še nisem uspel najti.

Tako da jaz bi predlagal, da se običajne pomišljaje uporablja kot '--'. Verjetno pa to niti ni zelo važno.
Aja še to: lahko do konca skomunicirava tudi preko drugega kanala, samo želel sem preizkusiti funkcionalnost Githuba. (Pa mogoče bi želel še kdo drug oddati svoj komentar.)
